### PR TITLE
Collision

### PR DESCRIPTION
**Pull request by EricLiu2000**

### CODE REVIEW

**Comment by bencw99** [comment]
Eric, take a look at the changes I made, we need to do a few things before merging with master. First of all, you had no comments for your functions, I added those in. Also, your collision function with dim and pos uses the position of this Entity as the UPPER LEFT corner rather than the center. So, assuming pos is the center of the dimensions, I wrote a function called get upper left which gets the upper left coordinates of the entity. You should incorporate this function into your collision detection.

**Comment by EricLiu2000** [comment]
I made the changes and also made a new upperleft function. and uh how do i make a new pull request for those changes?

**Comment by bencw99** [comment]
Instead of having two very similar upper left functions, why not just have your collision function take an Entity rather than a dim and a pos. This way, instead of using getUpperLeft(dim, pos), you could just say otherEntity.getUpperLeft() and only have one function. This also makes sense because you are checking for collision with an Entity, not an arbitrary dimension and position.And in response to your question, you use the same pull request.

**Comment by EricLiu2000** [comment]
done

**Pull request merged**
